[build]
builder = "dockerfile"
dockerfilePath = "api/Dockerfile"
buildCommand = ""

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
